package com.example.isaac_android_test

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.TextView
import com.example.isaac_android_test.ml.Model2
import org.tensorflow.lite.support.image.TensorImage

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val assetManager = this.assets
        val istr = assetManager.open("test_image.JPG") //The same image
        val b = BitmapFactory.decodeStream(istr)

        val model = Model2.newInstance(this) //Model definition generated by Android Studio

        // Creates inputs for reference.
        val image = TensorImage.fromBitmap(b)

        // Runs model inference and gets result.
        val outputs = model.process(image)
        val probability = outputs.probabilityAsCategoryList
        probability.sortByDescending { it.score }
        val top9 = probability.take(9)

        this.findViewById<TextView>(R.id.results_text).text = top9.toString()

        // Releases model resources if no longer used.
        model.close()
    }
}